[template]
src = "production.tmpl"
dest = "/opt/ansyn/app/assets/config/app.config.json"
keys = [
    "/ansyn/cases/baseurl",
    "/ansyn/layers/baseurl",
    "/ansyn/overlay/baseurl",
    "/ansyn/overlay/api/find",
    "/ansyn/overlay/api/default",
    "/ansyn/context/db/elastic/url",
    "/ansyn/context/db/proxy/url",
    "/ansyn/login/baseurl",
    "/ansyn/menu/background",
    "/ansyn/menu/color",
    "/ansyn/menu/mode"

]
